// Lloyd's CRS v5.2 — Motor PREMIUM columns (canonical column-spec table).
//
// Single long array literal — see `riskColumns.ts` for the rationale.

import type { CsrColumnSpec, PremiumRowCtx } from './types.js';
import {
  asRecord,
  mapRiskTransactionTypeForCr0022,
  resolvePremiumDerivedValues,
  toISODate,
} from './helpers.js';

export const CRS_V52_MOTOR_PREMIUM_COLUMNS: Array<CsrColumnSpec<PremiumRowCtx>> = [
  {
    key: 'cr0001',
    crCode: 'CR0001',
    title: 'CR0001 Reporting Period Start Date',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'high',
    sourceEntity: 'reportingPeriod',
    sourceField: 'startDate',
    sourceKind: 'constant',
    get: () => '',
  },
  {
    key: 'cr0002',
    crCode: 'CR0002',
    title: 'CR0002 Reporting Period End Date',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'high',
    sourceEntity: 'reportingPeriod',
    sourceField: 'endDate',
    sourceKind: 'constant',
    get: () => '',
  },
  {
    key: 'cr0013',
    crCode: 'CR0013',
    title: 'CR0013 Coverholder Name',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'high',
    sourceEntity: 'binder',
    sourceField: 'coverholderName',
    sourceKind: 'typed_column',
    authoritativeSource: true,
    get: (c) => c.binder?.coverholderName || '',
  },
  {
    key: 'cr0014',
    crCode: 'CR0014',
    title: 'CR0014 Coverholder PIN',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'medium',
    sourceEntity: 'binder',
    sourceField: 'coverholderPin',
    sourceKind: 'typed_column',
    authoritativeSource: true,
    get: (c) => c.binder?.coverholderPin || '',
  },
  {
    key: 'cr0005',
    crCode: 'CR0005',
    title: 'CR0005 UMR',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'high',
    sourceEntity: 'binder',
    sourceField: 'umr',
    sourceKind: 'typed_column',
    fallbackRule: 'policy.umr -> policy.policyNumber',
    get: (c) => c.binder?.umr || c.policy.umr || c.policy.policyNumber || '',
  },
  {
    key: 'cr0006',
    crCode: 'CR0006',
    title: 'CR0006 Agreement Number',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'high',
    sourceEntity: 'binder',
    sourceField: 'agreementNumber',
    sourceKind: 'typed_column',
    get: (c) => c.binder?.agreementNumber || '',
  },
  {
    key: 'cr0010',
    crCode: 'CR0010',
    title: 'CR0010 Year of Account',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'high',
    sourceEntity: 'binder',
    sourceField: 'config.reporting.yearOfAccount',
    sourcePath: '$.reporting.yearOfAccount',
    sourceKind: 'computed',
    fallbackRule: 'policy.inceptionDate.year',
    get: (c) => {
      const cfg = asRecord(c.binder?.config);
      const reporting = asRecord(cfg.reporting);
      const y = Number(reporting.yearOfAccount || new Date(String(c.policy.inceptionDate || '')).getFullYear() || '');
      return Number.isFinite(y) ? y : '';
    },
  },
  {
    key: 'cr0016',
    crCode: 'CR0016',
    title: 'CR0016 Risk Code',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'medium',
    sourceEntity: 'binder',
    sourceField: 'config.reporting.riskCode',
    sourcePath: '$.reporting.riskCode',
    sourceKind: 'json_snapshot',
    fallbackRule: 'AUTO_MOTOR',
    get: (c) => {
      const cfg = asRecord(c.binder?.config);
      const reporting = asRecord(cfg.reporting);
      return String(reporting.riskCode || 'AUTO_MOTOR');
    },
  },
  {
    key: 'cr0017',
    crCode: 'CR0017',
    title: 'CR0017 Class of Business',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'medium',
    sourceEntity: 'binder',
    sourceField: 'config.reporting.classOfBusiness',
    sourcePath: '$.reporting.classOfBusiness',
    sourceKind: 'json_snapshot',
    fallbackRule: 'MOTOR',
    get: (c) => {
      const cfg = asRecord(c.binder?.config);
      const reporting = asRecord(cfg.reporting);
      return String(reporting.classOfBusiness || 'MOTOR');
    },
  },
  {
    key: 'cr0019',
    crCode: 'CR0019',
    title: 'CR0019 Type of Insurance',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'high',
    sourceEntity: 'product',
    sourceField: 'insuranceType',
    sourceKind: 'constant',
    get: () => 'DIRECT',
  },
  {
    key: 'cr0026',
    crCode: 'CR0026',
    title: 'CR0026 Policy or Group Reference',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'high',
    sourceEntity: 'policy',
    sourceField: 'policyNumber',
    sourceKind: 'typed_column',
    get: (c) => c.policy.policyNumber || '',
  },
  {
    key: 'cr0029',
    crCode: 'CR0029',
    title: 'CR0029 Certificate Reference',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'high',
    sourceEntity: 'policy',
    sourceField: 'certificateNumber',
    sourceKind: 'typed_column',
    plainEnglishNote: 'Premium movements reuse policy certificate reference unless a dedicated endorsed schedule reference is introduced.',
    fallbackRule: 'policy.certificateReference',
    get: (c) => resolvePremiumDerivedValues(c).certificateRef,
  },
  {
    key: 'cr0035',
    crCode: 'CR0035',
    title: 'CR0035 Insured Name',
    requiredness: 'conditional',
    validationSeverity: 'warning',
    sourceReliability: 'high',
    sourceEntity: 'policyHolder',
    sourceField: 'name',
    sourceKind: 'typed_column',
    applicabilityKey: 'risk_not_submitted_separately',
    get: (c) => c.policyHolder?.name || '',
  },
  {
    key: 'cr0030',
    crCode: 'CR0030',
    title: 'CR0030 Risk Inception Date',
    requiredness: 'conditional',
    validationSeverity: 'warning',
    sourceReliability: 'high',
    sourceEntity: 'policy',
    sourceField: 'inceptionDate',
    sourceKind: 'typed_column',
    applicabilityKey: 'risk_not_submitted_separately',
    get: (c) => toISODate(c.policy.inceptionDate),
  },
  {
    key: 'cr0031',
    crCode: 'CR0031',
    title: 'CR0031 Risk Expiry Date',
    requiredness: 'conditional',
    validationSeverity: 'warning',
    sourceReliability: 'high',
    sourceEntity: 'policy',
    sourceField: 'expiryDate',
    sourceKind: 'typed_column',
    applicabilityKey: 'risk_not_submitted_separately',
    get: (c) => toISODate(c.policy.expiryDate),
  },
  {
    key: 'cr0022',
    crCode: 'CR0022',
    title: 'CR0022 Risk Transaction Type',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'high',
    sourceEntity: 'riskTransaction',
    sourceField: 'transactionType',
    sourceKind: 'typed_column',
    fallbackRule: 'maps INCEPTION/ENDORSEMENT/CANCELLATION -> NB/PAM/CAN',
    get: (c) => mapRiskTransactionTypeForCr0022(c.riskTransaction?.transactionType || 'INCEPTION'),
  },
  {
    key: 'cr0056',
    crCode: 'CR0056',
    title: 'CR0056 Premium Transaction Type',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'high',
    sourceEntity: 'premiumTransaction',
    sourceField: 'transactionType',
    sourceKind: 'typed_column',
    plainEnglishNote: 'Financial premium movement type for Lloyd’s export; not an internal workflow code.',
    derivationRule: 'issuance and movement-sign based mapping to Original/Additional/Return Premium',
    fallbackRule: 'NB/NB-COC/RNL->Original Premium; positive movement->Additional Premium; negative/refund->Return Premium',
    get: (c) => resolvePremiumDerivedValues(c).premiumTransactionType,
  },
  {
    key: 'cr0057',
    crCode: 'CR0057',
    title: 'CR0057 Effective Date of Transaction',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'high',
    sourceEntity: 'premiumTransaction',
    sourceField: 'createdAt',
    sourceKind: 'typed_column',
    get: (c) => toISODate(c.premiumTransaction?.createdAt),
  },
  {
    key: 'cr0058',
    crCode: 'CR0058',
    title: 'CR0058 Expiry Date of Transaction',
    requiredness: 'conditional',
    validationSeverity: 'warning',
    sourceReliability: 'high',
    sourceEntity: 'riskTransaction',
    sourceField: 'expiryDate',
    sourceKind: 'typed_column',
    applicabilityKey: 'premium_has_transaction_expiry',
    fallbackRule: 'policy.expiryDate',
    get: (c) => toISODate(c.riskTransaction?.expiryDate || c.policy.expiryDate),
  },
  {
    key: 'cr0059',
    crCode: 'CR0059',
    title: 'CR0059 Gross Premium Paid This Time',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'high',
    sourceEntity: 'premiumTransaction',
    sourceField: 'grossPremium',
    sourceKind: 'typed_column',
    fallbackRule: 'quoteResponse.primaryOption.annualPremium',
    get: (c) => resolvePremiumDerivedValues(c).grossMovement,
  },
  {
    key: 'cr0021',
    crCode: 'CR0021',
    title: 'CR0021 Total Gross Written Premium',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'high',
    sourceEntity: 'riskTransaction',
    sourceField: 'pricingFinal.premium',
    sourceKind: 'derived_projection',
    plainEnglishNote: 'Whole-risk written premium snapshot after the transaction movement, not just the row delta.',
    derivationRule: 'riskTransaction.pricingFinal premium after transaction',
    fallbackRule: 'premium gross movement (CR0059)',
    get: (c) => resolvePremiumDerivedValues(c).totalGrossWritten,
  },
  {
    key: 'cr0061',
    crCode: 'CR0061',
    title: 'CR0061 Commission Percentage',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'high',
    sourceEntity: 'premiumTransaction',
    sourceField: 'commissionPercent',
    sourceKind: 'typed_column',
    applicabilityKey: 'premium_has_commission',
    fallbackRule: 'binder.financials.commissionRate -> binder.config.reporting.commissionPercent -> 30',
    get: (c) => resolvePremiumDerivedValues(c).commissionPercent,
  },
  {
    key: 'cr0062',
    crCode: 'CR0062',
    title: 'CR0062 Commission Amount',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'high',
    sourceEntity: 'premiumTransaction',
    sourceField: 'commissionAmount',
    sourceKind: 'typed_column',
    applicabilityKey: 'premium_has_commission',
    derivationRule: 'CR0059 * CR0061 / 100',
    get: (c) => resolvePremiumDerivedValues(c).commissionAmount,
  },
  {
    key: 'cr0064',
    crCode: 'CR0064',
    title: 'CR0064 Total Taxes and Levies',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'high',
    sourceEntity: 'premiumTransaction',
    sourceField: 'taxesTotal',
    sourceKind: 'typed_column',
    plainEnglishNote: 'Tax bucket only (stamp duty). Do not include MIF surcharge in CR0064.',
    applicabilityKey: 'premium_has_taxes',
    derivationRule: 'stampDuty from pricing cost breakdown',
    fallbackRule: '2',
    get: (c) => resolvePremiumDerivedValues(c).stampDuty,
  },
  {
    key: 'cr0925',
    crCode: 'CR0925',
    title: 'CR0925 Total Fee Amount',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'high',
    sourceEntity: 'premiumTransaction',
    sourceField: 'feesTotal',
    sourceKind: 'typed_column',
    plainEnglishNote: 'Fee bucket only (MIF surcharge). Do not include stamp duty in CR0925.',
    applicabilityKey: 'premium_has_fees',
    derivationRule: 'mifSurcharge from pricing cost breakdown',
    fallbackRule: '9',
    get: (c) => resolvePremiumDerivedValues(c).mifSurcharge,
  },
  {
    key: 'cr0065',
    crCode: 'CR0065',
    title: 'CR0065 Net Premium to London (Original Currency)',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'high',
    sourceEntity: 'premiumTransaction',
    sourceField: 'netToLondon',
    sourceKind: 'typed_column',
    plainEnglishNote: 'Net to London is gross premium less commission. Fees/taxes are not subtracted from CR0065 in current model.',
    derivationRule: 'CR0059 - CR0062',
    get: (c) => resolvePremiumDerivedValues(c).netToLondon,
  },
  {
    key: 'cr0288',
    crCode: 'CR0288',
    title: 'CR0288 Number of Instalments',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'medium',
    sourceEntity: 'policy',
    sourceField: 'quoteData.numberOfInstalments',
    sourceKind: 'derived_projection',
    fallbackRule: '1',
    get: (c) => resolvePremiumDerivedValues(c).instalments,
  },
  {
    key: 'cr0289',
    crCode: 'CR0289',
    title: 'CR0289 Instalment Basis',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'medium',
    sourceEntity: 'policy',
    sourceField: 'quoteData.instalmentBasis',
    sourceKind: 'derived_projection',
    fallbackRule: 'Single',
    get: (c) => resolvePremiumDerivedValues(c).instalmentBasis,
  },
  {
    key: 'cr0066',
    crCode: 'CR0066',
    title: 'CR0066 Settlement Currency',
    requiredness: 'conditional',
    validationSeverity: 'warning',
    sourceReliability: 'high',
    sourceEntity: 'binder',
    sourceField: 'settlementCurrency',
    sourceKind: 'typed_column',
    applicabilityKey: 'settlement_currency_differs',
    fallbackRule: 'premiumTransaction.settlementCurrency -> premiumTransaction.currency',
    get: (c) => String(c.binder?.settlementCurrency || c.premiumTransaction?.settlementCurrency || c.premiumTransaction?.currency || ''),
  },
  {
    key: 'cr0067',
    crCode: 'CR0067',
    title: 'CR0067 Rate of Exchange',
    requiredness: 'conditional',
    validationSeverity: 'warning',
    sourceReliability: 'medium',
    sourceEntity: 'premiumTransaction',
    sourceField: 'fxRate',
    sourceKind: 'computed',
    applicabilityKey: 'settlement_currency_differs',
    fallbackRule: 'premiumTransaction.exchangeRate -> 1',
    get: (c) => {
      const fx = resolvePremiumDerivedValues(c).fxRate;
      return Number.isFinite(fx) && fx > 0 ? fx : 1;
    },
  },
  {
    key: 'cr0068',
    crCode: 'CR0068',
    title: 'CR0068 Net Premium to London (Settlement Currency)',
    requiredness: 'conditional',
    validationSeverity: 'warning',
    sourceReliability: 'medium',
    sourceEntity: 'premiumTransaction',
    sourceField: 'netToLondonSettlement',
    sourceKind: 'computed',
    applicabilityKey: 'settlement_currency_differs',
    fallbackRule: 'netToLondon * exchangeRate',
    get: (c) => {
      return resolvePremiumDerivedValues(c).netToLondonSettlement;
    },
  },
  {
    key: 'cr1297',
    crCode: 'CR1297',
    title: 'CR1297 Lloyds Platform',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'medium',
    sourceEntity: 'binder',
    sourceField: 'config.reporting.lloydsPlatform',
    sourceKind: 'json_snapshot',
    plainEnglishNote: 'Canonical source is binder reporting config; ABBEYGATE0125 uses LBS default until config is explicitly set.',
    fallbackRule: 'binder.reportingConfig.destinationPlatform -> binder.config.reporting.lloydsPlatform -> LBS for ABBEYGATE0125',
    get: (c) => resolvePremiumDerivedValues(c).lloydsPlatform,
  },
  {
    key: 'cr0077',
    crCode: 'CR0077',
    title: 'CR0077 Tax 1 Territory',
    requiredness: 'optional',
    validationSeverity: 'info',
    sourceReliability: 'medium',
    sourceEntity: 'taxLine',
    sourceField: 'jurisdiction',
    sourceKind: 'typed_column',
    get: (c) => String(resolvePremiumDerivedValues(c).taxLineOne.jurisdiction || ''),
  },
  {
    key: 'cr0078',
    crCode: 'CR0078',
    title: 'CR0078 Tax 1 Type',
    requiredness: 'optional',
    validationSeverity: 'info',
    sourceReliability: 'medium',
    sourceEntity: 'taxLine',
    sourceField: 'taxType',
    sourceKind: 'typed_column',
    get: (c) => String(resolvePremiumDerivedValues(c).taxLineOne.taxType || ''),
  },
  {
    key: 'cr0079',
    crCode: 'CR0079',
    title: 'CR0079 Tax 1 Taxable Amount',
    requiredness: 'optional',
    validationSeverity: 'info',
    sourceReliability: 'medium',
    sourceEntity: 'taxLine',
    sourceField: 'taxableAmount',
    sourceKind: 'typed_column',
    get: (c) => resolvePremiumDerivedValues(c).taxLineOne.taxableAmount ?? '',
  },
  {
    key: 'cr0080',
    crCode: 'CR0080',
    title: 'CR0080 Tax 1 Rate',
    requiredness: 'optional',
    validationSeverity: 'info',
    sourceReliability: 'medium',
    sourceEntity: 'taxLine',
    sourceField: 'rate',
    sourceKind: 'typed_column',
    plainEnglishNote: 'Intentionally blank when tax is fixed-amount and CR0081 is populated.',
    get: (c) => resolvePremiumDerivedValues(c).taxLineOne.rate ?? '',
  },
  {
    key: 'cr0081',
    crCode: 'CR0081',
    title: 'CR0081 Tax 1 Fixed Rate',
    requiredness: 'optional',
    validationSeverity: 'info',
    sourceReliability: 'medium',
    sourceEntity: 'taxLine',
    sourceField: 'fixedRate',
    sourceKind: 'typed_column',
    plainEnglishNote: 'For fixed-amount taxes (e.g. stamp duty), CR0081 is populated while CR0080 remains blank.',
    get: (c) => resolvePremiumDerivedValues(c).taxLineOne.fixedRate ?? '',
  },
  {
    key: 'cr0083',
    crCode: 'CR0083',
    title: 'CR0083 Tax 1 Amount',
    requiredness: 'optional',
    validationSeverity: 'info',
    sourceReliability: 'medium',
    sourceEntity: 'taxLine',
    sourceField: 'taxAmount',
    sourceKind: 'typed_column',
    get: (c) => resolvePremiumDerivedValues(c).taxLineOne.taxAmount ?? '',
  },
  {
    key: 'cr0020',
    crCode: 'CR0020',
    title: 'CR0020 Original Currency',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'high',
    sourceEntity: 'premiumTransaction',
    sourceField: 'currency',
    sourceKind: 'typed_column',
    fallbackRule: 'quoteResponse.currency -> binder.defaultCurrency -> EUR',
    get: (c) => c.premiumTransaction?.currency || c.policy.originalCurrency || c.quoteResponse?.currency || c.binder?.defaultCurrency || 'EUR',
  },
];

