// Lloyd's CRS v5.2 — Motor RISK columns (canonical column-spec table).
//
// Single long array literal — each entry is the spec for one
// CR-coded column. The natural seam was column-table-per-stream
// (risk / premium / claims), already extracted; splitting further
// would scatter the table without adding a real seam.

import type { CsrColumnSpec, RiskRowCtx } from './types.js';
import { asRecord, toISODate } from './helpers.js';

export const CRS_V52_MOTOR_RISK_COLUMNS: Array<CsrColumnSpec<RiskRowCtx>> = [
  {
    key: 'cr0001',
    crCode: 'CR0001',
    title: 'CR0001 Reporting Period Start Date',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'high',
    sourceEntity: 'reportingPeriod',
    sourceField: 'startDate',
    sourceKind: 'constant',
    get: () => '',
  },
  {
    key: 'cr0002',
    crCode: 'CR0002',
    title: 'CR0002 Reporting Period End Date',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'high',
    sourceEntity: 'reportingPeriod',
    sourceField: 'endDate',
    sourceKind: 'constant',
    get: () => '',
  },
  {
    key: 'cr0013',
    crCode: 'CR0013',
    title: 'CR0013 Coverholder Name',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'high',
    sourceEntity: 'binder',
    sourceField: 'coverholderName',
    sourceKind: 'typed_column',
    authoritativeSource: true,
    get: (c) => c.binder?.coverholderName || '',
  },
  {
    key: 'cr0014',
    crCode: 'CR0014',
    title: 'CR0014 Coverholder PIN',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'medium',
    sourceEntity: 'binder',
    sourceField: 'coverholderPin',
    sourceKind: 'typed_column',
    authoritativeSource: true,
    get: (c) => c.binder?.coverholderPin || '',
  },
  {
    key: 'cr0005',
    crCode: 'CR0005',
    title: 'CR0005 UMR',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'high',
    sourceEntity: 'binder',
    sourceField: 'umr',
    sourceKind: 'typed_column',
    fallbackRule: 'policy.umr -> policy.policyNumber',
    get: (c) => c.binder?.umr || c.policy.umr || c.policy.policyNumber || '',
  },
  {
    key: 'cr0006',
    crCode: 'CR0006',
    title: 'CR0006 Agreement Number',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'high',
    sourceEntity: 'binder',
    sourceField: 'agreementNumber',
    sourceKind: 'typed_column',
    get: (c) => c.binder?.agreementNumber || '',
  },
  {
    key: 'cr0010',
    crCode: 'CR0010',
    title: 'CR0010 Year of Account',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'high',
    sourceEntity: 'binder',
    sourceField: 'config.reporting.yearOfAccount',
    sourcePath: '$.reporting.yearOfAccount',
    sourceKind: 'computed',
    fallbackRule: 'policy.inceptionDate.year',
    get: (c) => {
      const cfg = asRecord(c.binder?.config);
      const reporting = asRecord(cfg.reporting);
      const y = Number(reporting.yearOfAccount || new Date(String(c.policy.inceptionDate || '')).getFullYear() || '');
      return Number.isFinite(y) ? y : '';
    },
  },
  {
    key: 'cr0016',
    crCode: 'CR0016',
    title: 'CR0016 Risk Code',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'medium',
    sourceEntity: 'binder',
    sourceField: 'config.reporting.riskCode',
    sourcePath: '$.reporting.riskCode',
    sourceKind: 'json_snapshot',
    fallbackRule: 'AUTO_MOTOR',
    get: (c) => {
      const cfg = asRecord(c.binder?.config);
      const reporting = asRecord(cfg.reporting);
      return String(reporting.riskCode || 'AUTO_MOTOR');
    },
  },
  {
    key: 'cr0017',
    crCode: 'CR0017',
    title: 'CR0017 Class of Business',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'medium',
    sourceEntity: 'binder',
    sourceField: 'config.reporting.classOfBusiness',
    sourcePath: '$.reporting.classOfBusiness',
    sourceKind: 'json_snapshot',
    fallbackRule: 'MOTOR',
    get: (c) => {
      const cfg = asRecord(c.binder?.config);
      const reporting = asRecord(cfg.reporting);
      return String(reporting.classOfBusiness || 'MOTOR');
    },
  },
  {
    key: 'cr0019',
    crCode: 'CR0019',
    title: 'CR0019 Type of Insurance',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'high',
    sourceEntity: 'product',
    sourceField: 'insuranceType',
    sourceKind: 'constant',
    get: () => 'DIRECT',
  },
  {
    key: 'cr0026',
    crCode: 'CR0026',
    title: 'CR0026 Policy or Group Reference',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'high',
    sourceEntity: 'policy',
    sourceField: 'policyNumber',
    sourceKind: 'typed_column',
    authoritativeSource: true,
    get: (c) => c.policy.policyNumber || '',
  },
  {
    key: 'cr0035',
    crCode: 'CR0035',
    title: 'CR0035 Insured Name',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'high',
    sourceEntity: 'policyHolder',
    sourceField: 'name',
    sourceKind: 'typed_column',
    get: (c) => c.policyHolder?.name || '',
  },
  {
    key: 'cr0030',
    crCode: 'CR0030',
    title: 'CR0030 Risk Inception Date',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'high',
    sourceEntity: 'policy',
    sourceField: 'inceptionDate',
    sourceKind: 'typed_column',
    get: (c) => toISODate(c.policy.inceptionDate),
  },
  {
    key: 'cr0031',
    crCode: 'CR0031',
    title: 'CR0031 Risk Expiry Date',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'high',
    sourceEntity: 'policy',
    sourceField: 'expiryDate',
    sourceKind: 'typed_column',
    get: (c) => toISODate(c.policy.expiryDate),
  },
  {
    key: 'cr0022',
    crCode: 'CR0022',
    title: 'CR0022 Risk Transaction Type',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'high',
    sourceEntity: 'riskTransaction',
    sourceField: 'transactionType',
    sourceKind: 'typed_column',
    fallbackRule: 'defaults to INCEPTION',
    get: (c) => c.riskTransaction?.transactionType || 'INCEPTION',
  },
  {
    key: 'cr0226',
    crCode: 'CR0226',
    title: 'CR0226 Country of Registration',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'medium',
    sourceEntity: 'policy',
    sourceField: 'quoteData.countryOfRegistration',
    sourcePath: '$.countryOfRegistration',
    sourceKind: 'json_snapshot',
    fallbackRule: 'policy.vehicleRegistrationCountry -> quoteData.countryOfRegistration',
    get: (c) => c.policy.vehicleRegistrationCountry || c.quoteData.countryOfRegistration || '',
  },
  {
    key: 'cr0033',
    crCode: 'CR0033',
    title: 'CR0033 Vehicle Registration Number',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'medium',
    sourceEntity: 'policy',
    sourceField: 'quoteData.registrationNumber',
    sourcePath: '$.registrationNumber',
    sourceKind: 'json_snapshot',
    fallbackRule: 'policy.vehicleRegistrationNumber -> quoteData.registrationNumber',
    get: (c) => c.policy.vehicleRegistrationNumber || (c.quoteData as Record<string, unknown>).registrationNumber || '',
  },
  {
    key: 'cr1275',
    crCode: 'CR1275',
    title: 'CR1275 Vehicle Type Code',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'medium',
    sourceEntity: 'policy',
    sourceField: 'quoteData.vehicleType',
    sourcePath: '$.vehicleType',
    sourceKind: 'json_snapshot',
    fallbackRule: 'policy.vehicleTypeCode -> quoteData.vehicleType',
    get: (c) => c.policy.vehicleTypeCode || c.quoteData.vehicleType || '',
  },
  {
    key: 'cr0377',
    crCode: 'CR0377',
    title: 'CR0377 Cover Type Level',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'medium',
    sourceEntity: 'policy',
    sourceField: 'quoteData.coverRequired',
    sourcePath: '$.coverRequired',
    sourceKind: 'json_snapshot',
    fallbackRule: 'policy.coverTypeCode -> quoteData.coverRequired',
    get: (c) => c.policy.coverTypeCode || c.quoteData.coverRequired || '',
  },
  {
    key: 'vehicleMake',
    title: 'Vehicle Make',
    requiredness: 'optional',
    validationSeverity: 'info',
    sourceReliability: 'medium',
    sourceEntity: 'policy',
    sourceField: 'quoteData.make',
    sourcePath: '$.make',
    sourceKind: 'json_snapshot',
    fallbackRule: 'quoteData.make',
    get: (c) => c.quoteData.make || '',
  },
  {
    key: 'vehicleModel',
    title: 'Vehicle Model',
    requiredness: 'optional',
    validationSeverity: 'info',
    sourceReliability: 'medium',
    sourceEntity: 'policy',
    sourceField: 'quoteData.model',
    sourcePath: '$.model',
    sourceKind: 'json_snapshot',
    fallbackRule: 'quoteData.model',
    get: (c) => c.quoteData.model || '',
  },
  {
    key: 'vehicleYear',
    title: 'Vehicle Year',
    requiredness: 'optional',
    validationSeverity: 'info',
    sourceReliability: 'medium',
    sourceEntity: 'policy',
    sourceField: 'quoteData.year',
    sourcePath: '$.year',
    sourceKind: 'json_snapshot',
    fallbackRule: 'quoteData.year',
    get: (c) => c.quoteData.year || '',
  },
  {
    key: 'engineSize',
    title: 'Engine Size',
    requiredness: 'optional',
    validationSeverity: 'info',
    sourceReliability: 'medium',
    sourceEntity: 'policy',
    sourceField: 'quoteData.engineSize',
    sourcePath: '$.engineSize',
    sourceKind: 'json_snapshot',
    fallbackRule: 'quoteData.engineSize',
    get: (c) => c.quoteData.engineSize || '',
  },
  {
    key: 'cr0052',
    crCode: 'CR0052',
    title: 'CR0052 Sum Insured Amount',
    requiredness: 'conditional',
    validationSeverity: 'warning',
    sourceReliability: 'medium',
    sourceEntity: 'policy',
    sourceField: 'quoteData.vehicleValue',
    sourcePath: '$.vehicleValue',
    sourceKind: 'json_snapshot',
    applicabilityKey: 'motor_own_damage',
    fallbackRule: 'policy.sumInsuredAmount -> quoteData.vehicleValue',
    get: (c) => c.policy.sumInsuredAmount || c.quoteData.vehicleValue || '',
  },
  {
    key: 'ncd',
    title: 'No Claims Discount',
    requiredness: 'optional',
    validationSeverity: 'info',
    sourceReliability: 'medium',
    sourceEntity: 'policy',
    sourceField: 'quoteData.ncb',
    sourcePath: '$.ncb',
    sourceKind: 'json_snapshot',
    fallbackRule: 'quoteData.ncb',
    get: (c) => c.quoteData.ncb || '',
  },
  {
    key: 'cr0054',
    crCode: 'CR0054',
    title: 'CR0054 Deductible/Excess Amount',
    requiredness: 'conditional',
    validationSeverity: 'warning',
    sourceReliability: 'medium',
    sourceEntity: 'policy',
    sourceField: 'quoteData.requiredExcess',
    sourcePath: '$.requiredExcess',
    sourceKind: 'json_snapshot',
    applicabilityKey: 'motor_has_excess',
    fallbackRule: 'policy.excessAmount -> quoteData.requiredExcess -> quoteResponse.primaryOption.totalExcess',
    get: (c) => c.policy.excessAmount || c.quoteData.requiredExcess || c.quoteResponse?.primaryOption?.totalExcess || '',
  },
  {
    key: 'cr0059',
    crCode: 'CR0059',
    title: 'CR0059 Gross Premium Paid This Time',
    requiredness: 'conditional',
    validationSeverity: 'warning',
    sourceReliability: 'medium',
    sourceEntity: 'policy',
    sourceField: 'quoteResponse.primaryOption.annualPremium',
    sourcePath: '$.primaryOption.annualPremium',
    sourceKind: 'json_snapshot',
    applicabilityKey: 'risk_level_financials_included',
    get: (c) => c.quoteResponse?.primaryOption?.annualPremium ?? '',
  },
  {
    key: 'cr0020',
    crCode: 'CR0020',
    title: 'CR0020 Original Currency',
    requiredness: 'mandatory',
    validationSeverity: 'error',
    sourceReliability: 'high',
    sourceEntity: 'policy',
    sourceField: 'quoteResponse.currency',
    sourcePath: '$.currency',
    sourceKind: 'json_snapshot',
    fallbackRule: 'binder.defaultCurrency -> EUR',
    get: (c) => c.policy.originalCurrency || c.quoteResponse?.currency || c.binder?.defaultCurrency || 'EUR',
  },
];
