import type { ProductGoldenFixtures } from '../../modules/policy/domain/productContracts.js';

/**
 * Phase 6k canonical motor golden fixtures. Personal-details live
 * exclusively under `proposer.*` (matching Travel + Home), and the
 * motor flat-shape aliases (`firstName`/`telephone`/`country`/…) have
 * been deleted from every code path. The Prisma
 * `canonicalize_motor_proposer` migration rewrites pre-existing rows.
 */
export const motorGoldenFixtures: ProductGoldenFixtures = {
  minimumValid: {
    proposer: {
      firstName: 'Ada',
      lastName: 'Lovelace',
      email: 'ada@example.com',
      phone: '+35799111222',
      dateOfBirth: '1988-01-01',
      address: {
        line1: '1 Conformance Street',
        city: 'Nicosia',
        province: 'Nicosia',
        postcode: '1000',
        country: 'Cyprus',
      },
      domicileCountry: 'Cyprus',
      // UK-national expat — operating-territory nationals (CY/PT/GR/ES/IT) refer.
      nationality: 'United Kingdom',
      nif: '12345678',
      occupation: 'Engineer',
      whereDidYouHear: 'Google',
      bestTimeToCall: 'Morning (09:00–12:00)',
      privacyPolicyAccepted: true,
      marketingConsent: false,
    },
    coverRequired: 'Comprehensive',
    renewalDate: new Date(Date.now() + 7 * 86_400_000).toISOString().slice(0, 10),
    vehicleType: 'Car',
    make: 'Toyota',
    model: 'Corolla',
    year: 2020,
    fuelType: 'Petrol',
    engineSize: 1800,
    vehicleValue: 30_000,
    kmsPerYear: '10,000',
    ncb: '2 Years',
    requiredExcess: '300',
    licenseYears: 8,
    licenseType: 'Full',
    licenseIssuedIn: 'Cyprus',
    countryOfRegistration: 'Cyprus',
    registrationNumber: 'CONF123',
    hasClaims: false,
    hasConvictions: false,
    driverRestriction: 'POLICYHOLDER_ONLY',
    hasAdditionalDrivers: false,
    additionalDrivers: [],
    vehicleUse: 'SD&P',
    infoTrueAndAccurate: true,
    fairProcessingAccepted: true,
  },
  referral: {
    proposer: {
      firstName: 'Ada',
      lastName: 'Referral',
      email: 'ada.referral@example.com',
      phone: '+35799111223',
      dateOfBirth: '2002-01-01',
    },
    coverRequired: 'Comprehensive',
    vehicleType: 'Car',
    make: 'Toyota',
    model: 'Corolla',
    year: 2020,
    engineSize: 1800,
    vehicleValue: 95_000,
    ncb: 'None',
    licenseYears: 1,
    licenseType: 'Full',
    licenseIssuedIn: 'Cyprus',
    countryOfRegistration: 'Cyprus',
    hasClaims: false,
    hasConvictions: false,
    driverRestriction: 'POLICYHOLDER_ONLY',
    hasAdditionalDrivers: false,
    vehicleUse: 'SD&P',
  },
  decline: {
    proposer: {
      firstName: 'Ada',
      lastName: 'Decline',
      email: 'ada.decline@example.com',
      phone: '+35799111224',
      dateOfBirth: '2005-01-01',
    },
    coverRequired: 'Comprehensive',
    vehicleType: 'Car',
    make: 'Toyota',
    model: 'Corolla',
    year: 2020,
    engineSize: 1800,
    vehicleValue: 300_000,
    ncb: 'None',
    licenseYears: 0,
    licenseType: 'Provisional',
    licenseIssuedIn: 'Cyprus',
    countryOfRegistration: 'Cyprus',
    hasClaims: false,
    hasConvictions: false,
    driverRestriction: 'POLICYHOLDER_ONLY',
    hasAdditionalDrivers: false,
    vehicleUse: 'SD&P',
  },
};
