// Explicit synthetic user entries for the canonical offline intake. Never runtime defaults.
export const candidateFormValues: Record<string, string> = {
  'proposer.firstName': 'Alex',
  'proposer.lastName': 'Example',
  'proposer.email': 'alex@example.invalid',
  'proposer.phone': '+12025550101',
  'proposer.address.line1': '1 Synthetic Way',
  'proposer.address.city': 'Denver',
  'proposer.address.postalCode': '80202',
  'driver.age': '30',
  'driver.licenceNumber': 'SYNTHETIC-LICENCE',
  'driver.licenceCountry': 'US',
  'driver.licenceValid': 'true',
  'driver.namedOnRentalAgreement': 'true',
  'vehicle.make': 'Toyota',
  'vehicle.model': 'Corolla',
  'vehicle.trim': 'Synthetic trim',
  'vehicle.class': 'compact',
  'vehicle.year': '2025',
  'vehicle.value': '24000',
  'driver.fullName': 'Alex Example',
  'driver.namedOnAgreement': 'true',
  'driver.firstName': 'Alex',
  'driver.lastName': 'Example',
  'vehicle.registration': 'DEMO-001',
  'rentalAgreement.reference': 'DEMO-RENTAL-001',
};
