import type { EndorsementGroup } from '../../modules/policy/domain/productContracts.js';
import type { EndorsementTemplate } from '../../modules/mbe/domain/types.js';

export const TRAVEL_ENDORSEMENT_TEMPLATES: EndorsementTemplate[] = [
  {
    id: 'tmpl-travel-base-cover',
    program_code: 'abbeygate_travel',
    code: 'TRAVEL-BASE-COVER',
    title: 'Travel Insurance',
    summary: 'Base travel cover determined by cover type, plan level, area of travel, traveller type, traveller ages, and trip duration.',
    type: 'COVERAGE',
    scope: 'POLICY',
    jurisdiction: ['CY', 'GR', 'EU', 'WORLD'],
    legal_text: 'Core schedule line showing policy type, area, level, maximum trip duration, insured persons, and premium.',
    parameters_schema: {
      type: 'object',
      properties: {
        typeOfCover: { type: 'string' },
        levelOfCover: { type: 'string' },
        areaOfTravel: { type: 'string' },
        travellerType: { type: 'string' },
        days: { type: 'number' },
        maxTripDuration: { type: 'number' },
      },
      required: [],
    },
    default_params: {},
    rules: {
      prerequisites: [],
      exclusions: [],
      effects: [],
      approval: { requires_underwriter: false },
    },
    option_defaults: { enabledByDefault: true },
    ui: { group: 'core', help_text: 'Core travel cover. Silver / Gold / Platinum remain base plan tiers, not optional add-ons.', form_fields: [] },
    document_template: 'travel-base-cover.html',
    requires_underwriter_approval: false,
    allowed_with: [],
    disallowed_with: [],
  },
  {
    id: 'tmpl-travel-winter-sports',
    program_code: 'abbeygate_travel',
    code: 'TRAVEL-WINTER-SPORTS',
    title: 'Winter Sports',
    summary: 'Optional winter sports extension.',
    type: 'COVER_EXTENSION',
    scope: 'POLICY',
    jurisdiction: ['EU', 'WORLD'],
    legal_text: 'Optional Extensions: Winter Sports.',
    parameters_schema: {
      type: 'object',
      properties: {
        travellerCount: { type: 'number' },
      },
      required: [],
    },
    default_params: {},
    rules: {
      prerequisites: [],
      exclusions: [],
      effects: [],
      approval: { requires_underwriter: false },
    },
    option_defaults: { enabledByDefault: false, selectedWhen: [{ path: 'addons.winterSports', equals: true }] },
    ui: { group: 'sports', help_text: 'Single Trip: 100% loading. Annual Multi Trip: EUR 50 per traveller.', form_fields: [] },
    document_template: 'travel-winter-sports.html',
    requires_underwriter_approval: false,
    allowed_with: [],
    disallowed_with: [],
  },
  {
    id: 'tmpl-travel-business-cover',
    program_code: 'abbeygate_travel',
    code: 'TRAVEL-BUSINESS-COVER',
    title: 'Business Cover',
    summary: 'Optional business travel extension.',
    type: 'COVER_EXTENSION',
    scope: 'POLICY',
    jurisdiction: ['EU', 'WORLD'],
    legal_text: 'Optional Extensions: Business Cover.',
    parameters_schema: {
      type: 'object',
      properties: {
        travellerCount: { type: 'number' },
      },
      required: [],
    },
    default_params: {},
    rules: {
      prerequisites: [],
      exclusions: [],
      effects: [],
      approval: { requires_underwriter: false },
    },
    option_defaults: { enabledByDefault: false, selectedWhen: [{ path: 'addons.businessCover', equals: true }] },
    ui: { group: 'business', help_text: 'EUR 20 per traveller.', form_fields: [] },
    document_template: 'travel-business-cover.html',
    requires_underwriter_approval: false,
    allowed_with: [],
    disallowed_with: [],
  },
  {
    id: 'tmpl-travel-golf-cover',
    program_code: 'abbeygate_travel',
    code: 'TRAVEL-GOLF-COVER',
    title: 'Golf Cover',
    summary: 'Optional golf travel extension.',
    type: 'COVER_EXTENSION',
    scope: 'POLICY',
    jurisdiction: ['EU', 'WORLD'],
    legal_text: 'Optional Extensions: Golf Cover.',
    parameters_schema: {
      type: 'object',
      properties: {
        travellerCount: { type: 'number' },
      },
      required: [],
    },
    default_params: {},
    rules: {
      prerequisites: [],
      exclusions: [],
      effects: [],
      approval: { requires_underwriter: false },
    },
    option_defaults: { enabledByDefault: false, selectedWhen: [{ path: 'addons.golfCover', equals: true }] },
    ui: { group: 'sports', help_text: 'EUR 10 per traveller.', form_fields: [] },
    document_template: 'travel-golf-cover.html',
    requires_underwriter_approval: false,
    allowed_with: [],
    disallowed_with: [],
  },
  {
    id: 'tmpl-travel-terrorism',
    program_code: 'abbeygate_travel',
    code: 'TRAVEL-TERRORISM',
    title: 'Terrorism Cover',
    summary: 'Optional terrorism buy-back extension.',
    type: 'COVER_EXTENSION',
    scope: 'POLICY',
    jurisdiction: ['EU', 'WORLD'],
    legal_text: 'Optional Extensions: Terrorism Cover.',
    parameters_schema: {
      type: 'object',
      properties: {
        travellerCount: { type: 'number' },
      },
      required: [],
    },
    default_params: {},
    rules: {
      prerequisites: [],
      exclusions: [],
      effects: [],
      approval: { requires_underwriter: false },
    },
    option_defaults: { enabledByDefault: false, selectedWhen: [{ path: 'addons.terrorism', equals: true }] },
    ui: { group: 'extras', help_text: 'EUR 10 per traveller. Buy-back of terrorism exclusion.', form_fields: [] },
    document_template: 'travel-terrorism.html',
    requires_underwriter_approval: false,
    allowed_with: [],
    disallowed_with: [],
  },
  {
    id: 'tmpl-travel-sports-equipment',
    program_code: 'abbeygate_travel',
    code: 'TRAVEL-SPORTS-EQUIPMENT',
    title: 'Sports / Cycle Equipment',
    summary: 'Cover for loss, theft or damage to sports or cycle equipment and the cost of hiring replacements.',
    type: 'COVER_EXTENSION',
    scope: 'POLICY',
    jurisdiction: ['EU', 'WORLD'],
    legal_text: 'Optional Extensions: Sports/Cycle Equipment.',
    parameters_schema: {
      type: 'object',
      properties: {
        travellerCount: { type: 'number' },
      },
      required: [],
    },
    default_params: {},
    rules: {
      prerequisites: [],
      exclusions: [],
      effects: [],
      approval: { requires_underwriter: false },
    },
    option_defaults: { enabledByDefault: false, selectedWhen: [{ path: 'addons.sportsEquipment', equals: true }] },
    ui: { group: 'sports', help_text: '10% of base premium per traveller.', form_fields: [] },
    document_template: 'travel-sports-equipment.html',
    requires_underwriter_approval: false,
    allowed_with: [],
    disallowed_with: [],
  },
  {
    id: 'tmpl-travel-wedding',
    program_code: 'abbeygate_travel',
    code: 'TRAVEL-WEDDING',
    title: 'Wedding',
    summary: 'Cover for wedding attire, rings, gifts, and loss of photographs or video recordings.',
    type: 'COVER_EXTENSION',
    scope: 'POLICY',
    jurisdiction: ['EU', 'WORLD'],
    legal_text: 'Optional Extensions: Wedding.',
    parameters_schema: {
      type: 'object',
      properties: {
        travellerCount: { type: 'number' },
      },
      required: [],
    },
    default_params: {},
    rules: {
      prerequisites: [],
      exclusions: [],
      effects: [],
      approval: { requires_underwriter: false },
    },
    option_defaults: { enabledByDefault: false, selectedWhen: [{ path: 'addons.wedding', equals: true }] },
    ui: { group: 'extras', help_text: '15% of base premium per traveller.', form_fields: [] },
    document_template: 'travel-wedding.html',
    requires_underwriter_approval: false,
    allowed_with: [],
    disallowed_with: [],
  },
  {
    id: 'tmpl-travel-gadget',
    program_code: 'abbeygate_travel',
    code: 'TRAVEL-GADGET',
    title: 'Gadget',
    summary: 'Extra protection for gadgets against accidental damage, theft, loss, liquid damage and unauthorised usage.',
    type: 'COVER_EXTENSION',
    scope: 'POLICY',
    jurisdiction: ['EU', 'WORLD'],
    legal_text: 'Optional Extensions: Gadget.',
    parameters_schema: {
      type: 'object',
      properties: {
        travellerCount: { type: 'number' },
      },
      required: [],
    },
    default_params: {},
    rules: {
      prerequisites: [],
      exclusions: [],
      effects: [],
      approval: { requires_underwriter: false },
    },
    option_defaults: { enabledByDefault: false, selectedWhen: [{ path: 'addons.gadget', equals: true }] },
    ui: { group: 'extras', help_text: '10% of base premium per traveller.', form_fields: [] },
    document_template: 'travel-gadget.html',
    requires_underwriter_approval: false,
    allowed_with: [],
    disallowed_with: [],
  },
];

export const TRAVEL_ENDORSEMENT_GROUPS: EndorsementGroup[] = [
  { id: 'core', title: 'Core', templates: ['TRAVEL-BASE-COVER'] },
  { id: 'sports', title: 'Sports', templates: ['TRAVEL-WINTER-SPORTS', 'TRAVEL-GOLF-COVER', 'TRAVEL-SPORTS-EQUIPMENT'] },
  { id: 'business', title: 'Business', templates: ['TRAVEL-BUSINESS-COVER'] },
  { id: 'extras', title: 'Extras', templates: ['TRAVEL-TERRORISM', 'TRAVEL-WEDDING', 'TRAVEL-GADGET'] },
];
