{{- if .Values.keyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.keyVault.secretProviderClassName }}
  labels:
    {{- include "abbeygate.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.keyVault.clientId | quote }}
    keyvaultName: {{ .Values.keyVault.name | quote }}
    tenantId: {{ .Values.keyVault.tenantId | quote }}
    objects: |
      array:
      {{- range .Values.keyVault.objects }}
        - |
          objectName: {{ .name }}
          objectType: secret
      {{- end }}
  secretObjects:
    - secretName: {{ .Values.runtimeConfig.secretName }}
      type: Opaque
      data:
      {{- range .Values.keyVault.objects }}
        - objectName: {{ .name }}
          key: {{ .key }}
      {{- end }}
{{- end }}
