import type { InsuranceConfiguration } from '../../../modules/insuranceConfiguration/domain/runtimeConfiguration.js';
import { compileProcessChannels, compileProposalQuestionnaire } from '../../../modules/insuranceConfiguration/domain/runtimeConfiguration.js';
import type { BuildQuoteResponseContext } from '../../../modules/policy/domain/productContracts.js';
export function syntheticCommercialConfiguration(): InsuranceConfiguration {
  return { schemaVersion: 1, process: { businessDescription: 'Synthetic commercial training; no customer authority', considerations: [], recommendedPackage: 'QUOTE_SYMPHONY', customers: { forms: true, approve: true, docs: true, portal: false, pay: false, claim: false, cancel: false }, agents: { enabled: false, contractTypes: [], deltaBonus: [], commissionMode: 'none', showExpectedCommission: false, cancellationRule: 'proRata', permissions: [] } }, product: { name: 'Synthetic commercial training', classOfBusinessKey: 'training', status: 'Active', active: true, coverageSections: [{ classOfBusinessKey: 'training', coverageName: 'Training liability', includedClauseIds: ['training-clause'], excludedClauseIds: [], territorialLimit: 'Synthetic sandbox only', notes: 'No real insurance authority', maxLimit: '1000000', deductible: '100' }], details: { proposalQuestionGroups: [{ name: 'Commercial risk', questions: [{ id: 'turnover', slug: 'commercial.turnover', field: 'Annual turnover', answerType: 'Number', coverage: 'All', required: true, settings: { minNumber: 0, maxNumber: 1000000000 } }] }], primaryCoverage: { kind: 'Training liability' }, professions: [{ section: 'Training', profession: 'Training business', segmentId: 'training-business', calcMethod: 'Risk Code', riskCodesByCoverage: { 'Training liability': 'TRAINING-1' } }], calculationsByCoverage: { 'Training liability': { riskCodeTable: [{ code: 'TRAINING-1', baseRate: '0.5' }], minimumPremiumFloor: 100, enforceMinimumPremium: true } }, wordingClauses: { training: [{ id: 'training-clause', coverageType: 'Training liability', name: 'Training wording', category: 'Clause', mode: 'Mandatory (Locked)', linkedTo: 'All', status: 'Active', body: 'Synthetic training only. No insurance cover is provided.', isManual: true, source: 'manual' }] } } } };
}
export function commercialContext(configuration = syntheticCommercialConfiguration(), definitionId = 'definition-a'): BuildQuoteResponseContext {
  const brand = { brokerDisplayName: 'Training A', brokerLegalName: 'Training organization', brokerAddressMultiline: 'Synthetic address', brokerAddressOneLine: 'Synthetic address', brokerRegulatoryLine: 'No regulatory authority asserted', uwTeamName: 'Training operators', coverholderStatement: 'Synthetic training only', dataControllerName: 'Training organization' };
  return { programDefinition: { id: definitionId, programId: 'programme', version: 1, pricingMode: 'AUTOMATED', binderProductAuthorityId: 'authority', underwriting: { schemaVersion: 1, mode: 'automatic_acceptance', reason: 'Explicit synthetic training decision' }, coverage: { schemaVersion: 1, programCode: 'commercial', base: [{ code: 'COMMERCIAL_POLICY', enabled: true }], options: [] }, questionnaire: compileProposalQuestionnaire(configuration.product), workflow: { referralOnly: false, externalIssuance: { mode: 'NONE' }, insuranceConfiguration: configuration }, channels: compileProcessChannels(configuration), documents: { productKit: { schemaVersion: 1, programCode: 'commercial', brand } } }, ratingModel: { id: 'model', programId: 'programme', version: 1, binderProductAuthorityId: 'authority', tables: { schemaVersion: 1, engine: 'symphony-commercial-v1', configurationSource: 'programme_definition' }, stages: [{ id: 'commercial', operator: 'symphony-commercial-v1' }] } };
}
