[target.wasm32-unknown-unknown]
rustflags = ["-C", "link-arg=--stack-first", "-C", "link-arg=-z", "-C", "link-arg=stack-size=65536", "-C", "link-arg=--initial-memory=131072", "-C", "link-arg=--max-memory=131072"]
