import type { EndorsementGroup } from '../../modules/policy/domain/productContracts.js';
import type { EndorsementTemplate } from '../../modules/mbe/domain/types.js';

export const HOME_ENDORSEMENT_TEMPLATES: EndorsementTemplate[] = [
  {
    id: 'tmpl-home-buildings',
    program_code: 'abbeygate_home',
    code: 'HOME-BUILDINGS',
    title: 'Buildings',
    summary: 'Core buildings cover shown when buildings sum insured exists.',
    type: 'COVERAGE',
    scope: 'RISK_OBJECT',
    jurisdiction: ['CY', 'GR'],
    legal_text: 'A. Buildings EUR [amount]. Buildings cover including the schedule excess structure and any applicable subsidence, heave, or landslip excess.',
    parameters_schema: {
      type: 'object',
      properties: {
        sumInsured: { type: 'number' },
        excess: { type: 'number' },
        escapeOfWaterExcess: { type: 'number' },
        earthquakeVolcanicExcess: { type: 'number' },
        subsidenceExcess: { type: 'number' },
      },
      required: ['sumInsured'],
    },
    default_params: {},
    rules: {
      prerequisites: [
        { type: 'policy_flag', key: 'homeHasBuildings', value: true, message: 'Buildings cover requires a buildings sum insured greater than zero.' },
      ],
      exclusions: [],
      effects: [],
      approval: { requires_underwriter: false },
    },
    option_defaults: { enabledByDefault: true },
    ui: { group: 'property', help_text: 'A. Buildings EUR [amount]', form_fields: [] },
    document_template: 'home-buildings.html',
    requires_underwriter_approval: false,
    allowed_with: [],
    disallowed_with: [],
  },
  {
    id: 'tmpl-home-contents',
    program_code: 'abbeygate_home',
    code: 'HOME-CONTENTS',
    title: 'Contents in the home',
    summary: 'Core contents cover shown when contents sum insured exists.',
    type: 'COVERAGE',
    scope: 'RISK_OBJECT',
    jurisdiction: ['CY', 'GR'],
    legal_text: 'B. Contents in the home EUR [amount], including the applicable single article, valuables, and outbuildings limits shown on the schedule.',
    parameters_schema: {
      type: 'object',
      properties: {
        sumInsured: { type: 'number' },
        singleArticleLimit: { type: 'number' },
        valuablesTotalLimit: { type: 'number' },
        outbuildingsLimit: { type: 'number' },
      },
      required: ['sumInsured'],
    },
    default_params: {},
    rules: {
      prerequisites: [
        { type: 'policy_flag', key: 'homeHasContents', value: true, message: 'Contents cover requires a contents sum insured greater than zero.' },
      ],
      exclusions: [],
      effects: [],
      approval: { requires_underwriter: false },
    },
    option_defaults: { enabledByDefault: true },
    ui: { group: 'property', help_text: 'B. Contents in the home EUR [amount]', form_fields: [] },
    document_template: 'home-contents.html',
    requires_underwriter_approval: false,
    allowed_with: [],
    disallowed_with: [],
  },
  {
    id: 'tmpl-home-liability',
    program_code: 'abbeygate_home',
    code: 'HOME-LIABILITY',
    title: 'Liability',
    summary: 'Included public liability cover.',
    type: 'PROTECTION',
    scope: 'POLICY',
    jurisdiction: ['CY', 'GR'],
    legal_text: 'Liability included, indemnity EUR 1,000,000.',
    parameters_schema: {
      type: 'object',
      properties: {
        limit: { type: 'number' },
      },
      required: ['limit'],
    },
    default_params: { limit: 1000000 },
    rules: {
      prerequisites: [],
      exclusions: [],
      effects: [],
      approval: { requires_underwriter: false },
    },
    option_defaults: { enabledByDefault: true },
    ui: { group: 'liability', help_text: 'Liability included at EUR 1,000,000.', form_fields: [] },
    document_template: 'home-liability.html',
    requires_underwriter_approval: false,
    allowed_with: [],
    disallowed_with: [],
  },
  {
    id: 'tmpl-home-emergency-travel',
    program_code: 'abbeygate_home',
    code: 'HOME-EMERGENCY-TRAVEL',
    title: 'Emergency Travel',
    summary: 'Included emergency travel and accommodation assistance.',
    type: 'ASSISTANCE',
    scope: 'POLICY',
    jurisdiction: ['CY', 'GR'],
    legal_text: 'Emergency Travel Included. Return ticket limit EUR 350, accommodation and expenses EUR 600, aggregate EUR 1,500 per period.',
    parameters_schema: {
      type: 'object',
      properties: {
        returnTicketLimit: { type: 'number' },
        accommodationExpensesLimit: { type: 'number' },
        aggregatePeriodLimit: { type: 'number' },
      },
      required: ['returnTicketLimit', 'accommodationExpensesLimit', 'aggregatePeriodLimit'],
    },
    default_params: {
      returnTicketLimit: 350,
      accommodationExpensesLimit: 600,
      aggregatePeriodLimit: 1500,
    },
    rules: {
      prerequisites: [],
      exclusions: [],
      effects: [],
      approval: { requires_underwriter: false },
    },
    option_defaults: { enabledByDefault: true },
    ui: { group: 'assistance', help_text: 'Emergency Travel Included', form_fields: [] },
    document_template: 'home-emergency-travel.html',
    requires_underwriter_approval: false,
    allowed_with: [],
    disallowed_with: [],
  },
  {
    id: 'tmpl-home-acc-damage-buildings',
    program_code: 'abbeygate_home',
    code: 'HOME-ACC-DAMAGE-BUILDINGS',
    title: 'Accidental Damage to Buildings',
    summary: 'Optional accidental damage extension for buildings.',
    type: 'COVER_EXTENSION',
    scope: 'RISK_OBJECT',
    jurisdiction: ['CY', 'GR'],
    legal_text: 'Accidental Damage to Buildings: Included.',
    parameters_schema: { type: 'object', properties: {}, required: [] },
    default_params: {},
    rules: {
      prerequisites: [
        { type: 'policy_flag', key: 'homeHasBuildings', value: true, message: 'Requires Buildings cover.' },
      ],
      exclusions: [],
      effects: [],
      approval: { requires_underwriter: false },
    },
    option_defaults: { enabledByDefault: false },
    ui: { group: 'property', help_text: 'Optional accidental damage extension for buildings.', form_fields: [] },
    document_template: 'home-acc-damage-buildings.html',
    requires_underwriter_approval: false,
    allowed_with: [],
    disallowed_with: [],
  },
  {
    id: 'tmpl-home-acc-damage-contents',
    program_code: 'abbeygate_home',
    code: 'HOME-ACC-DAMAGE-CONTENTS',
    title: 'Accidental Damage to Contents',
    summary: 'Optional accidental damage extension for contents.',
    type: 'COVER_EXTENSION',
    scope: 'RISK_OBJECT',
    jurisdiction: ['CY', 'GR'],
    legal_text: 'Accidental Damage to Contents: Included.',
    parameters_schema: { type: 'object', properties: {}, required: [] },
    default_params: {},
    rules: {
      prerequisites: [
        { type: 'policy_flag', key: 'homeHasContents', value: true, message: 'Requires Contents cover.' },
      ],
      exclusions: [],
      effects: [],
      approval: { requires_underwriter: false },
    },
    option_defaults: { enabledByDefault: false },
    ui: { group: 'property', help_text: 'Optional accidental damage extension for contents.', form_fields: [] },
    document_template: 'home-acc-damage-contents.html',
    requires_underwriter_approval: false,
    allowed_with: [],
    disallowed_with: [],
  },
  {
    id: 'tmpl-home-valuables-pe',
    program_code: 'abbeygate_home',
    code: 'HOME-VALUABLES-PE',
    title: 'High Risk Items and Personal Effects',
    summary: 'European all-risks cover for high risk items and personal effects.',
    type: 'COVER_EXTENSION',
    scope: 'POLICY',
    jurisdiction: ['CY', 'GR', 'EU'],
    legal_text: 'C. High Risk Items and personal effects — European All Risks cover.',
    parameters_schema: {
      type: 'object',
      properties: {
        jewelleryAmount: { type: 'number' },
        personalEffectsAmount: { type: 'number' },
        singleArticleLimit: { type: 'number' },
      },
      required: [],
    },
    default_params: {
      jewelleryAmount: 0,
      personalEffectsAmount: 0,
      singleArticleLimit: 0,
    },
    rules: {
      prerequisites: [],
      exclusions: [],
      effects: [],
      approval: { requires_underwriter: false },
    },
    option_defaults: { enabledByDefault: false },
    ui: {
      group: 'valuables',
      help_text: 'European all-risks cover for high risk items and personal effects.',
      form_fields: [
        { name: 'jewelleryAmount', label: 'High risk items amount', type: 'currency', required: false },
        { name: 'personalEffectsAmount', label: 'Personal effects amount', type: 'currency', required: false },
        { name: 'singleArticleLimit', label: 'Single article limit', type: 'currency', required: false },
      ],
    },
    document_template: 'home-valuables-pe.html',
    requires_underwriter_approval: false,
    allowed_with: [],
    disallowed_with: [],
  },
  {
    id: 'tmpl-home-safe-high-risk',
    program_code: 'abbeygate_home',
    code: 'HOME-SAFE-HIGH-RISK',
    title: 'AB106 Safe Conditions',
    summary: 'Safe condition applied automatically when specified high risk items are insured.',
    type: 'CONDITION',
    scope: 'POLICY',
    jurisdiction: ['CY', 'GR', 'EU'],
    // Verbatim Beazley/Lloyd's coverholder wording (AB106). The clause is
    // "only operative if shown on Your Schedule" — so it is attached to the
    // schedule automatically whenever the policy insures specified high risk
    // items (see backend/products/home/documents/viewModel.ts).
    legal_text:
      'AB106 Safe Conditions: This insurance excludes theft in respect of any jewellery or watches or any other valuables from the Home unless: a. such items are kept in a locked safe or strongbox weighing over 100kgs which must not be in an open position or, b. in a safe which is anchored to or completely embedded in the wall or floor, suitably concealed. Whenever the premises are left unattended by You or any authorised representatives, all keys and duplicate keys to the safe must be removed from the Home.',
    parameters_schema: { type: 'object', properties: {}, required: [] },
    default_params: {},
    rules: {
      prerequisites: [],
      exclusions: [],
      effects: [],
      approval: { requires_underwriter: false },
    },
    option_defaults: { enabledByDefault: false },
    ui: { group: 'valuables', help_text: 'Safe condition for specified high risk items (AB106).', form_fields: [] },
    document_template: 'home-safe-high-risk.html',
    requires_underwriter_approval: false,
    allowed_with: [],
    disallowed_with: [],
  },
  {
    id: 'tmpl-home-europ-assistance',
    program_code: 'abbeygate_home',
    code: 'HOME-EUROP-ASSISTANCE',
    title: 'Europ Assistance Home Emergency Assistance',
    summary: 'Partner emergency home assistance service.',
    type: 'ASSISTANCE',
    scope: 'POLICY',
    jurisdiction: ['CY', 'GR'],
    legal_text: 'Emergency assistance coverage for the home — electrician, plumber, emergency locksmith or glazier.',
    parameters_schema: {
      type: 'object',
      properties: {
        provider: { type: 'string' },
        premium_eur: { type: 'number' },
      },
      required: ['provider', 'premium_eur'],
    },
    default_params: {
      provider: 'Europ Assistance',
      premium_eur: 12,
    },
    rules: {
      prerequisites: [],
      exclusions: [],
      effects: [],
      approval: { requires_underwriter: false },
    },
    option_defaults: { enabledByDefault: true },
    ui: { group: 'assistance', help_text: 'Emergency assistance coverage for the home.', form_fields: [] },
    document_template: 'home-europ-assistance.html',
    requires_underwriter_approval: false,
    allowed_with: [],
    disallowed_with: [],
  },
];

export const HOME_ENDORSEMENT_GROUPS: EndorsementGroup[] = [
  { id: 'property', title: 'Property', templates: ['HOME-BUILDINGS', 'HOME-CONTENTS', 'HOME-ACC-DAMAGE-BUILDINGS', 'HOME-ACC-DAMAGE-CONTENTS'] },
  { id: 'valuables', title: 'Valuables', templates: ['HOME-VALUABLES-PE', 'HOME-SAFE-HIGH-RISK'] },
  { id: 'liability', title: 'Liability', templates: ['HOME-LIABILITY'] },
  { id: 'assistance', title: 'Assistance', templates: ['HOME-EMERGENCY-TRAVEL', 'HOME-EUROP-ASSISTANCE'] },
];
